version: '3'

services:
  users-1:
    container_name: users-1
    build:
      context: ./users
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    networks:
      - micromon

  users-2:
    container_name: users-2
    build:
      context: ./users
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    networks:
      - micromon

  posts-1:
    container_name: posts-1
    build:
      context: ./posts
      dockerfile: Dockerfile
    environment:
      - PORT=3002
    networks:
      - micromon

  posts-2:
    container_name: posts-2
    build:
      context: ./posts
      dockerfile: Dockerfile
    environment:
      - PORT=3002
    networks:
      - micromon

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - users-1
      - users-2
      - posts-1
      - posts-2
    ports:
      - '8080:80'
    networks:
      - micromon

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - users-1
      - users-2
      - posts-1
      - posts-2
    networks:
      - micromon

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/prometheus-datasource.yml
    depends_on:
      - prometheus
    networks:
      - micromon

networks:
  micromon:

volumes:
  grafana-data:
