global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'users'
    static_configs:
      - targets: ['users-1:3001', 'users-2:3001']

  - job_name: 'posts'
    static_configs:
      - targets: ['posts-1:3002', 'posts-2:3002']
